/**
 * Production static server for the NWC-Analytics frontend.
 *
 * Replaces `serve -s build`. It does everything `serve` did (static assets,
 * SPA fallback, the /sitemap.xml -> API 301 redirect) via the same underlying
 * `serve-handler`, PLUS one extra job:
 *
 *   Server-side Open Graph / Twitter injection for /blogs/:slug.
 *
 * Why this lives here and not in FastAPI: nwc-analytics.com is served by THIS
 * service (behind Cloudflare). Social scrapers (Reddit, Facebook, X, Discord,
 * LinkedIn) don't run JS and never reach the API service, so React 19's
 * client-side <meta> hoisting is invisible to them. They read whatever static
 * HTML this server returns. Without injection, every shared blog link shows the
 * homepage's default preview card. Here we look the post up (via the existing
 * public API) and rewrite the OG block before serving.
 *
 * Fail-soft contract: the blog lookup must NEVER break page serving. Any miss,
 * timeout, or error falls back to the unmodified index.html shell — React then
 * renders the page (or its not-found state) client-side exactly as before.
 *
 * Marker strategy: CRA's production build minifies index.html with
 * removeComments:true, so HTML-comment markers (<!-- OG:START -->) do NOT
 * survive `npm run build`. Instead we key off the stable semantic attributes
 * (property="og:*" / name="twitter:*") — robust to minification and tag order.
 */
const http = require('http');
const path = require('path');
const fs = require('fs');
const handler = require('serve-handler');

const PORT = process.env.PORT || 3000;
const BUILD_DIR = path.join(__dirname, 'build');
const INDEX_PATH = path.join(BUILD_DIR, 'index.html');

// Backend base URL for the server-to-server blog lookup. Same public API the
// browser uses; override with OG_API_BASE if a private URL is preferred.
const API_BASE = (process.env.OG_API_BASE || 'https://api.nwc-analytics.com').replace(/\/+$/, '');
const SITE_ORIGIN = 'https://nwc-analytics.com';
const DEFAULT_OG_IMAGE = `${SITE_ORIGIN}/images/og-default.png`;
const POST_TTL_MS = 60_000;     // in-memory cache per the task's guidance
const FETCH_TIMEOUT_MS = 4_000; // keep scrapers fast; on timeout we serve the shell

// Read the shell once at startup — never hit disk per request.
let INDEX_HTML;
try {
  INDEX_HTML = fs.readFileSync(INDEX_PATH, 'utf8');
} catch (err) {
  console.error(`[server] FATAL: could not read ${INDEX_PATH}. Did you run "npm run build"?`, err.message);
  process.exit(1);
}

// serve-handler config mirroring the old build/serve.json exactly:
//   - SPA fallback: any unmatched path -> /index.html
//   - /sitemap.xml -> API (the sitemap is generated by FastAPI)
// Static files that exist on disk are served directly (rewrites only apply to
// paths with no matching file), so /static/*, /images/*, /robots.txt etc. work.
const HANDLER_CONFIG = {
  public: BUILD_DIR,
  redirects: [
    { source: '/sitemap.xml', destination: `${API_BASE}/sitemap.xml`, type: 301 },
  ],
  rewrites: [
    { source: '**', destination: '/index.html' },
  ],
};

// ── Helpers ────────────────────────────────────────────────────────────────

/** HTML-escape for use inside a double-quoted attribute. */
function esc(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Meta-description fallback for posts without an excerpt: first ~155 chars of
 * the body with HTML stripped, cut at a word boundary. Mirrors deriveDescription
 * in src/pages/BlogPost.tsx so scraper and browser descriptions match.
 */
function deriveDescription(html) {
  const text = String(html || '')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (text.length <= 155) return text;
  const cut = text.slice(0, 155);
  const lastSpace = cut.lastIndexOf(' ');
  return `${lastSpace > 0 ? cut.slice(0, lastSpace) : cut}…`;
}

/** Normalize a cover-image URL to an absolute https URL, or null if unusable. */
function absoluteImage(url) {
  if (!url || !String(url).trim()) return null;
  const u = String(url).trim();
  if (u.startsWith('//')) return `https:${u}`;
  if (u.startsWith('http://')) return `https://${u.slice('http://'.length)}`;
  if (u.startsWith('https://')) return u;
  if (u.startsWith('/')) return `${SITE_ORIGIN}${u}`;
  return `${SITE_ORIGIN}/${u}`;
}

/**
 * Build the per-post <head> tags and splice them into the shell:
 *   1. remove the default og:* / twitter:* meta tags
 *   2. replace the <title>
 *   3. insert the post-specific block (title-suffixed OG/Twitter + description)
 *      right before </head>
 * Uses replacer FUNCTIONS everywhere so `$` in post text is never treated as a
 * regex backreference.
 */
function injectOg(html, post) {
  const title = (post.title && String(post.title).trim()) || 'NWC-Analytics';
  const ogTitle = `${title} | NWC-Analytics`;
  const description =
    (post.excerpt && String(post.excerpt).trim()) ||
    deriveDescription(post.content) ||
    `${title} — stock analysis insights from NWC-Analytics.`;
  const image = absoluteImage(post.cover_image_url) || DEFAULT_OG_IMAGE;
  const url = `${SITE_ORIGIN}/blogs/${encodeURIComponent(post.slug || '')}`;

  const block =
    `<title>${esc(ogTitle)}</title>` +
    `<meta name="description" content="${esc(description)}"/>` +
    `<meta property="og:type" content="article"/>` +
    `<meta property="og:site_name" content="NWC-Analytics"/>` +
    `<meta property="og:title" content="${esc(ogTitle)}"/>` +
    `<meta property="og:description" content="${esc(description)}"/>` +
    `<meta property="og:image" content="${esc(image)}"/>` +
    `<meta property="og:url" content="${esc(url)}"/>` +
    `<meta name="twitter:card" content="summary_large_image"/>` +
    `<meta name="twitter:title" content="${esc(ogTitle)}"/>` +
    `<meta name="twitter:description" content="${esc(description)}"/>` +
    `<meta name="twitter:image" content="${esc(image)}"/>`;

  return html
    // 1. drop default OG + Twitter meta tags (keyed off stable attributes)
    .replace(/<meta\b[^>]*\b(?:property="og:[^"]*"|name="twitter:[^"]*")[^>]*>/gi, () => '')
    // 2. drop the default <title> (the new one is added in the block below)
    .replace(/<title>[\s\S]*?<\/title>/i, () => '')
    // 3. splice the post-specific block in just before </head>
    .replace(/<\/head>/i, () => `${block}</head>`);
}

// ── Blog post lookup (cached, fail-soft) ────────────────────────────────────

const postCache = new Map(); // slug -> { at, post }  (post === null means "known miss")

async function fetchPost(slug) {
  const now = Date.now();
  const cached = postCache.get(slug);
  if (cached && now - cached.at < POST_TTL_MS) return cached.post;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(`${API_BASE}/api/v1/content/blogs/${encodeURIComponent(slug)}`, {
      signal: controller.signal,
      headers: { Accept: 'application/json' },
    });
    if (res.status === 404) {
      postCache.set(slug, { at: now, post: null }); // cache misses briefly
      return null;
    }
    if (!res.ok) return null; // transient upstream error — don't cache, retry next time
    const post = await res.json();
    postCache.set(slug, { at: now, post });
    return post;
  } catch (err) {
    // Network error / timeout / abort — fail soft, do not cache.
    console.warn(`[server] blog lookup failed for "${slug}": ${err.message}`);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

const BLOG_PATH_RE = /^\/blogs\/([^/]+)\/?$/;

const server = http.createServer(async (req, res) => {
  try {
    if (req.method === 'GET' || req.method === 'HEAD') {
      const pathname = new URL(req.url, `http://${req.headers.host || 'localhost'}`).pathname;
      const match = pathname.match(BLOG_PATH_RE);
      if (match) {
        const slug = decodeURIComponent(match[1]);
        const post = await fetchPost(slug); // null => serve default shell (fail-soft)
        const body = post ? injectOg(INDEX_HTML, post) : INDEX_HTML;
        res.writeHead(200, {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=0, must-revalidate',
        });
        res.end(req.method === 'HEAD' ? undefined : body);
        return;
      }
    }
  } catch (err) {
    // Anything unexpected: fall through to the static handler, which serves the
    // SPA shell. Serving must never 500 because of the OG feature.
    console.error('[server] request handling error, falling back to static:', err.message);
  }
  return handler(req, res, HANDLER_CONFIG);
});

server.listen(PORT, () => {
  console.log(`[server] NWC-Analytics frontend on :${PORT} (API_BASE=${API_BASE})`);
});
