/**
 * Production static server for the NWC-Analytics frontend.
 *
 * Replaces `serve -s build`. It does everything `serve` did (static assets,
 * SPA fallback, the /sitemap.xml -> API 301 redirect) via the same underlying
 * `serve-handler`, PLUS one extra job:
 *
 *   Server-side Open Graph / Twitter injection for /blogs/:slug.
 *
 * Why this lives here and not in FastAPI: nwc-analytics.com is served by THIS
 * service (behind Cloudflare). Social scrapers (Reddit, Facebook, X, Discord,
 * LinkedIn) don't run JS and never reach the API service, so React 19's
 * client-side <meta> hoisting is invisible to them. They read whatever static
 * HTML this server returns. Without injection, every shared blog link shows the
 * homepage's default preview card. Here we look the post up (via the existing
 * public API) and rewrite the OG block before serving.
 *
 * Fail-soft contract: the blog lookup must NEVER break page serving. Any miss,
 * timeout, or error falls back to the unmodified index.html shell — React then
 * renders the page (or its not-found state) client-side exactly as before.
 *
 * Marker strategy: CRA's production build minifies index.html with
 * removeComments:true, so HTML-comment markers (<!-- OG:START -->) do NOT
 * survive `npm run build`. Instead we key off the stable semantic attributes
 * (property="og:*" / name="twitter:*") — robust to minification and tag order.
 */
const http = require('http');
const path = require('path');
const fs = require('fs');
const handler = require('serve-handler');
const ogImage = require('./og-image');

const PORT = process.env.PORT || 3000;
const BUILD_DIR = path.join(__dirname, 'build');
const INDEX_PATH = path.join(BUILD_DIR, 'index.html');

// Backend base URL for the server-to-server blog lookup. Same public API the
// browser uses; override with OG_API_BASE if a private URL is preferred.
const API_BASE = (process.env.OG_API_BASE || 'https://api.nwc-analytics.com').replace(/\/+$/, '');
const SITE_ORIGIN = 'https://nwc-analytics.com';
const POST_TTL_MS = 60_000;        // blog-post lookup cache per the task's guidance
const FETCH_TIMEOUT_MS = 4_000;    // HTML injection path: keep scrapers fast
const OG_FETCH_TIMEOUT_MS = 2_000; // image path: shorter — it has a safe default-card fallback
const OG_CACHE_CAP = 100;          // rendered-PNG cache cap (blog is ~40 posts)

// Read the shell once at startup — never hit disk per request.
let INDEX_HTML;
try {
  INDEX_HTML = fs.readFileSync(INDEX_PATH, 'utf8');
} catch (err) {
  console.error(`[server] FATAL: could not read ${INDEX_PATH}. Did you run "npm run build"?`, err.message);
  process.exit(1);
}

// serve-handler config mirroring the old build/serve.json exactly:
//   - SPA fallback: any unmatched path -> /index.html
//   - /sitemap.xml -> API (the sitemap is generated by FastAPI)
// Static files that exist on disk are served directly (rewrites only apply to
// paths with no matching file), so /static/*, /images/*, /robots.txt etc. work.
const HANDLER_CONFIG = {
  public: BUILD_DIR,
  redirects: [
    { source: '/sitemap.xml', destination: `${API_BASE}/sitemap.xml`, type: 301 },
  ],
  rewrites: [
    { source: '**', destination: '/index.html' },
  ],
};

// ── Helpers ────────────────────────────────────────────────────────────────

/** HTML-escape for use inside a double-quoted attribute. */
function esc(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Reduce HTML (or a raw excerpt) to plain text: drop script/style, strip tags,
 * decode the handful of entities that show up in our content, collapse
 * whitespace. No truncation — callers truncate per target with truncate().
 */
function stripToText(html) {
  return String(html || '')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Truncate to `max` chars at a word boundary, appending "…" only if cut. The
 * ellipsis is counted within the budget so the result never exceeds `max`.
 */
function truncate(text, max) {
  const s = String(text || '').replace(/\s+/g, ' ').trim();
  if (s.length <= max) return s;
  const slice = s.slice(0, max - 1);
  const lastSpace = slice.lastIndexOf(' ');
  const base = (lastSpace > 0 ? slice.slice(0, lastSpace) : slice).replace(/[\s.,;:!?—–-]+$/, '');
  return `${base}…`;
}

/** Normalize a cover-image URL to an absolute https URL, or null if unusable. */
function absoluteImage(url) {
  if (!url || !String(url).trim()) return null;
  const u = String(url).trim();
  if (u.startsWith('//')) return `https:${u}`;
  if (u.startsWith('http://')) return `https://${u.slice('http://'.length)}`;
  if (u.startsWith('https://')) return u;
  if (u.startsWith('/')) return `${SITE_ORIGIN}${u}`;
  return `${SITE_ORIGIN}/${u}`;
}

/**
 * Build the per-post <head> tags and splice them into the shell:
 *   1. remove the default og:* / twitter:* meta tags
 *   2. replace the <title>
 *   3. insert the post-specific block (title-suffixed OG/Twitter + description)
 *      right before </head>
 * Uses replacer FUNCTIONS everywhere so `$` in post text is never treated as a
 * regex backreference.
 */
function injectOg(html, post) {
  const title = (post.title && String(post.title).trim()) || 'NWC-Analytics';
  const ogTitle = `${title} | NWC-Analytics`;

  const base =
    stripToText(post.excerpt) ||
    stripToText(post.content) ||
    `${title} — stock analysis insights from NWC-Analytics.`;
  const ogDescription = truncate(base, 125);   // social preview cards truncate ~125
  const metaDescription = truncate(base, 155); // Google truncates ~150–160

  // og:image points at the dynamic card renderer (/og/{slug}.png -> 1200x630).
  // FUTURE (out of scope): if post.cover_image_url is a real, non-logo image,
  // prefer it here via absoluteImage(post.cover_image_url). Kept as a rendered
  // card for now so every post gets a correctly-sized, on-brand preview.
  const image = `${SITE_ORIGIN}/og/${encodeURIComponent(post.slug || '')}.png`;
  const url = `${SITE_ORIGIN}/blogs/${encodeURIComponent(post.slug || '')}`;

  const block =
    `<title>${esc(ogTitle)}</title>` +
    `<meta name="description" content="${esc(metaDescription)}"/>` +
    `<meta property="og:type" content="article"/>` +
    `<meta property="og:site_name" content="NWC-Analytics"/>` +
    `<meta property="og:title" content="${esc(ogTitle)}"/>` +
    `<meta property="og:description" content="${esc(ogDescription)}"/>` +
    `<meta property="og:image" content="${esc(image)}"/>` +
    `<meta property="og:image:width" content="1200"/>` +
    `<meta property="og:image:height" content="630"/>` +
    `<meta property="og:url" content="${esc(url)}"/>` +
    `<meta name="twitter:card" content="summary_large_image"/>` +
    `<meta name="twitter:title" content="${esc(ogTitle)}"/>` +
    `<meta name="twitter:description" content="${esc(ogDescription)}"/>` +
    `<meta name="twitter:image" content="${esc(image)}"/>`;

  return html
    // 1. drop default OG + Twitter meta tags (keyed off stable attributes)
    .replace(/<meta\b[^>]*\b(?:property="og:[^"]*"|name="twitter:[^"]*")[^>]*>/gi, () => '')
    // 2. drop the default <title> (the new one is added in the block below)
    .replace(/<title>[\s\S]*?<\/title>/i, () => '')
    // 3. splice the post-specific block in just before </head>
    .replace(/<\/head>/i, () => `${block}</head>`);
}

// ── Blog post lookup (cached, fail-soft) ────────────────────────────────────

const postCache = new Map(); // slug -> { at, post }  (post === null means "known miss")

async function fetchPost(slug, timeoutMs = FETCH_TIMEOUT_MS) {
  const now = Date.now();
  const cached = postCache.get(slug);
  if (cached && now - cached.at < POST_TTL_MS) return cached.post;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`${API_BASE}/api/v1/content/blogs/${encodeURIComponent(slug)}`, {
      signal: controller.signal,
      headers: { Accept: 'application/json' },
    });
    if (res.status === 404) {
      postCache.set(slug, { at: now, post: null }); // cache misses briefly
      return null;
    }
    if (!res.ok) return null; // transient upstream error — don't cache, retry next time
    const post = await res.json();
    postCache.set(slug, { at: now, post });
    return post;
  } catch (err) {
    // Network error / timeout / abort — fail soft, do not cache.
    console.warn(`[server] blog lookup failed for "${slug}": ${err.message}`);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

// ── OG image rendering (cached, fail-soft) ──────────────────────────────────

const ogCache = new Map(); // key -> PNG Buffer (small LRU)

function ogCacheGet(key) {
  const buf = ogCache.get(key);
  if (buf === undefined) return undefined;
  ogCache.delete(key); // move to most-recent
  ogCache.set(key, buf);
  return buf;
}

function ogCacheSet(key, buf) {
  ogCache.delete(key);
  ogCache.set(key, buf);
  while (ogCache.size > OG_CACHE_CAP) ogCache.delete(ogCache.keys().next().value); // evict oldest
}

/**
 * Render (or serve cached) the OG card PNG for a slug. "default" -> site card.
 * Any lookup miss/timeout falls back to the default card. Throws only if even
 * the default card can't render (fonts missing) — the caller then redirects to
 * the static logo so a scraper never gets a 500.
 */
async function getOgPng(slug) {
  const key = slug === 'default' ? 'default' : `post:${slug}`;
  const cached = ogCacheGet(key);
  if (cached) return cached;

  let png;
  if (slug === 'default') {
    png = await ogImage.renderDefaultCard();
  } else {
    const post = await fetchPost(slug, OG_FETCH_TIMEOUT_MS); // shorter ceiling; safe fallback below
    if (post) {
      try {
        png = await ogImage.renderPostCard(post);
      } catch (err) {
        console.warn(`[server] post card render failed for "${slug}", using default: ${err.message}`);
        png = await ogImage.renderDefaultCard();
      }
    } else {
      png = await ogImage.renderDefaultCard(); // unknown slug / API down -> default card, still 200
    }
  }
  ogCacheSet(key, png);
  return png;
}

async function handleOgImage(rawSlug, req, res) {
  const slug = decodeURIComponent(rawSlug);
  try {
    const png = await getOgPng(slug);
    res.writeHead(200, { 'Content-Type': 'image/png', 'Cache-Control': 'public, max-age=86400' });
    res.end(req.method === 'HEAD' ? undefined : png);
  } catch (err) {
    // Last-resort fail-soft: never 500 a scraper — redirect to the static logo.
    console.error(`[server] OG image unavailable for "${slug}", redirecting to logo: ${err.message}`);
    res.writeHead(302, { Location: '/images/logo.png', 'Cache-Control': 'public, max-age=300' });
    res.end();
  }
}

const OG_PATH_RE = /^\/og\/(.+)\.png$/;
const BLOG_PATH_RE = /^\/blogs\/([^/]+)\/?$/;

const server = http.createServer(async (req, res) => {
  try {
    if (req.method === 'GET' || req.method === 'HEAD') {
      const pathname = new URL(req.url, `http://${req.headers.host || 'localhost'}`).pathname;

      // Dynamic OG cards — must be handled before the SPA fallback.
      const ogMatch = pathname.match(OG_PATH_RE);
      if (ogMatch) {
        await handleOgImage(ogMatch[1], req, res);
        return;
      }

      const match = pathname.match(BLOG_PATH_RE);
      if (match) {
        const slug = decodeURIComponent(match[1]);
        const post = await fetchPost(slug); // null => serve default shell (fail-soft)
        const body = post ? injectOg(INDEX_HTML, post) : INDEX_HTML;
        res.writeHead(200, {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=0, must-revalidate',
        });
        res.end(req.method === 'HEAD' ? undefined : body);
        return;
      }
    }
  } catch (err) {
    // Anything unexpected: fall through to the static handler, which serves the
    // SPA shell. Serving must never 500 because of the OG feature.
    console.error('[server] request handling error, falling back to static:', err.message);
  }
  return handler(req, res, HANDLER_CONFIG);
});

server.listen(PORT, () => {
  console.log(`[server] NWC-Analytics frontend on :${PORT} (API_BASE=${API_BASE})`);
});
