"""Add portfolio_transactions ledger + backfill a synthetic BUY per position

Revision ID: 030
Revises: 029
Create Date: 2026-08-19

Append-only buy/sell ledger backing the portfolio Sell feature. Nothing is ever
deleted from this table; a mistyped sale is corrected by appending a REVERSAL
row. The `portfolio` table stays as the materialized current-holdings
projection (quantity + average cost).

Hand-written, not autogenerated: alembic/env.py sets target_metadata = None,
so --autogenerate produces an empty migration in this project.

BACKFILL LOSSINESS (deliberate, and unrecoverable either way): existing
positions were built by add_position's weighted-average merge, which already
discarded the individual purchases. The synthetic opening BUY therefore carries
the *average* cost, which is exactly what average-cost accounting needs. It
only matters for a future FIFO implementation, which will have to treat
pre-migration holdings as a single opening lot at average cost.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '030'
down_revision = '029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'portfolio_transactions',
        sa.Column('id', postgresql.UUID(as_uuid=True),
                  server_default=sa.text('gen_random_uuid()'), primary_key=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True),
                  sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('ticker', sa.String(10), nullable=False),
        sa.Column('transaction_type', sa.String(10), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('transaction_date', sa.Date(), nullable=False),
        sa.Column('cost_basis_per_share', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('realized_pl', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('reverses_transaction_id', postgresql.UUID(as_uuid=True),
                  sa.ForeignKey('portfolio_transactions.id'), nullable=True, unique=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.CheckConstraint(
            "transaction_type IN ('BUY', 'SELL', 'ADJUST', 'REVERSAL')",
            name='ck_portfolio_tx_type',
        ),
        sa.CheckConstraint(
            "(transaction_type IN ('BUY', 'SELL', 'REVERSAL') AND quantity > 0) "
            "OR (transaction_type = 'ADJUST' AND quantity >= 0)",
            name='ck_portfolio_tx_quantity',
        ),
        sa.CheckConstraint('price > 0', name='ck_portfolio_tx_price'),
        sa.CheckConstraint(
            "transaction_type NOT IN ('SELL', 'REVERSAL') "
            "OR (cost_basis_per_share IS NOT NULL AND realized_pl IS NOT NULL)",
            name='ck_portfolio_tx_sell_basis',
        ),
        sa.CheckConstraint(
            "(transaction_type = 'REVERSAL') = (reverses_transaction_id IS NOT NULL)",
            name='ck_portfolio_tx_reversal_link',
        ),
    )

    op.create_index('idx_portfolio_tx_user_date', 'portfolio_transactions',
                    ['user_id', 'transaction_date'])
    op.create_index('idx_portfolio_tx_user_ticker', 'portfolio_transactions',
                    ['user_id', 'ticker'])

    # ---- Backfill: one synthetic opening BUY per existing position ----
    # created_at is copied from the position row so ledger ordering matches the
    # real timeline rather than the migration's run time.
    #
    # The quantity/buy_price guards are load-bearing, not cosmetic: migrations
    # auto-run at startup via migration_runner.py, so a single junk row (e.g. a
    # 0-quantity position left by the old ORM `default=0`) tripping a CHECK
    # constraint would turn a failed migration into a failed boot.
    op.execute(
        """
        INSERT INTO portfolio_transactions (
            user_id, ticker, transaction_type, quantity, price,
            transaction_date, cost_basis_per_share, realized_pl, notes, created_at
        )
        SELECT
            p.user_id,
            UPPER(p.ticker),
            'BUY',
            p.quantity,
            p.buy_price,
            p.buy_date,
            NULL,
            NULL,
            'Opening position backfilled by migration 030',
            COALESCE(p.created_at, CURRENT_TIMESTAMP)
        FROM portfolio p
        WHERE p.quantity > 0
          AND p.buy_price > 0
        """
    )


def downgrade() -> None:
    # DESTRUCTIVE: drops every recorded sale and all realized P/L history.
    # The `portfolio` projection is untouched, so current holdings survive.
    op.drop_index('idx_portfolio_tx_user_ticker', table_name='portfolio_transactions')
    op.drop_index('idx_portfolio_tx_user_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
