"""Add kind discriminator to saved_screens

Revision ID: 031
Revises: 030
Create Date: 2026-08-20

The table now holds two things: screener screens (criteria = the full screener
filter payload) and Stock Search keyword searches (criteria = {"query": "..."}).
They share one table and one tier limit; `kind` keeps the two lists apart when
each tab loads its own.

Hand-written, not autogenerated: alembic/env.py sets target_metadata = None,
so --autogenerate produces an empty migration in this project.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '031'
down_revision = '030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'saved_screens',
        sa.Column('kind', sa.String(20), nullable=False, server_default='screener'),
    )
    op.create_index('idx_saved_screens_user_kind', 'saved_screens', ['user_id', 'kind'])


def downgrade() -> None:
    op.drop_index('idx_saved_screens_user_kind', table_name='saved_screens')
    op.drop_column('saved_screens', 'kind')
